name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.8.2'
          cabal-version: '3.2'
      - name: Update stack
        run: |
          stack update
      - name: Stack install
        run: |
          stack install --flag fltkhs:bundled
      - name: Stack build
        run: |
          stack build

